# Default values for ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: livekit/ingress
  pullPolicy: IfNotPresent

ingress:
  log_level: info
  api_key: access_token
  api_secret: 2ea28d33c5fd79804210fef46d9b97ea287fa4
  ws_url: wss://media1ws.cluster.meetmo.io
  insecure: true
  redis:
      address: db-redis-nyc1-63688-do-user-13370465-0.b.db.ondigitalocean.com:25061
      db: 0
      username: default
      password: AVNS_bTx9GKCWilylnRIz4ME
      use_tls: true
  
  health_port: 7888
  prometheus_port: 7889
  http_relay_port: 9090
  rtmp_port: 1935
  
  cpu_cost:
    rtmp_cpu_cost: 2

loadBalancer:
  servicePort: 7888
  annotations: {}

terminationGracePeriodSeconds: 3600

nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: true

nodeSelector: {}

resources: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"
  linkerd.io/inject: disabled

podSecurityContext: {}

securityContext: {}

tolerations: []

affinity: {}
