
# Livekit server
apiVersion: v1
kind: ConfigMap
metadata:
  name: lk-server
data:
  config.yaml: |
    keys:
      access_token: 2ea28d33c5fd79804210fef46d9b97ea287fa4
    
    log_level: debug
    port: 7880
    
    redis:
      address: db-redis-nyc1-63688-do-user-13370465-0.b.db.ondigitalocean.com:25061
      db: 0
      username: default
      password: AVNS_bTx9GKCWilylnRIz4ME
      use_tls: true
        
    room:
      max_participants: 0
      enabled_codecs:
        - mime: audio/opus
        - mime: video/vp9
        - mime: video/av1
        - mime: video/vp8    
    rtc:
      port_range_end: 60000
      port_range_start: 50000
      tcp_port: 7801
      stun_servers:
        - relay1.cluster.meetmo.io:443
      turn_servers:
      - credential: pass-1
        host: relay1.cluster.meetmo.io
        port: 443
        protocol: tls
        username: user-1
      use_external_ip: false
    
    ingress:
      rtmp_base_url: rtmp://stream.meetmo.io/live
    
    turn:
      enabled: false
      loadBalancerAnnotations: {}

---
apiVersion: v1
kind: Service
metadata:
  name: lk-server
  labels:
    app.kubernetes.io/name: lk-server
    app.kubernetes.io/instance: livekit
    app.kubernetes.io/version: "latest"
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 7880
      protocol: TCP
      name: http
    - port: 7801
      targetPort: 7801
      protocol: TCP
      name: rtc-tcp
 
  selector:
    app.kubernetes.io/name: lk-server
    app.kubernetes.io/instance: livekit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lk-server
  labels:
    app.kubernetes.io/name: lk-server
    app.kubernetes.io/instance: livekit
    app.kubernetes.io/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lk-server
      app.kubernetes.io/instance: livekit
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/name: lk-server
        app.kubernetes.io/instance: livekit
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 18000 # 5 hours
      containers:
        - name: lk-server
          image: "livekit/livekit-server:latest"
          imagePullPolicy: IfNotPresent
          args: ["--disable-strict-config"]
          env:
            - name: LIVEKIT_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: lk-server
                  key: config.yaml

            - name: LIVEKIT_AV1_PARAMS_PROFILE
              value: "2"
            - name: LIVEKIT_AV1_PARAMS_LEVEL
              value: "2.1"
            - name: LIVEKIT_VP9_PARAMS_PROFILE_ID
              value: "2"
            - name: LIVEKIT_VP9_PARAMS_BITRATE
              value: "1000000"
            - name: LIVEKIT_SVC
              value: "true"
            - name: LIVEKIT_SIMULCAST_MODE
              value: "svc"
            - name: LIVEKIT_SIMULCAST_NUM_STREAMS
              value: "3"
            - name: LIVEKIT_SIMULCAST_SCALING_MODES
              value: "resolution,resolution,resolution"
            - name: LIVEKIT_SIMULCAST_RIDS
              value: "f,h,q"
            
          ports:
            - name: http
              containerPort: 7880
              protocol: TCP
            - name: rtc-tcp
              containerPort: 7801
              protocol: TCP

          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 128Mi
      
      